### In this notebook we will practice the tensors using tensorflow

In [1]:
# import libraries
import tensorflow as tf
import numpy as np

In [2]:
# creating 0d tensor
tensor_zero=tf.constant(4)
print("0D tensor is\n",tensor_zero)
print("="*50)

# creating 1d tensors
tensor_1d=tf.constant([1,2,3,4,5])
print("1D tensor is\n",tensor_1d)
print("="*50)

# creating 2d tensors
tensor_2d=tf.constant([[1,2,3,4], [4,3,2,1]])
print("2D tensor is\n", tensor_2d)
print("="*50)

# creating 3d tensors
tensor_3d=tf.constant([
    [[1,2,3,4], 
    [4,3,2,1]],

    [[-1,2,5,8],
    [5,6,78,9]]
])
print("3D tensor is\n",tensor_3d)

0D tensor is
 tf.Tensor(4, shape=(), dtype=int32)
1D tensor is
 tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
2D tensor is
 tf.Tensor(
[[1 2 3 4]
 [4 3 2 1]], shape=(2, 4), dtype=int32)
3D tensor is
 tf.Tensor(
[[[ 1  2  3  4]
  [ 4  3  2  1]]

 [[-1  2  5  8]
  [ 5  6 78  9]]], shape=(2, 2, 4), dtype=int32)


### Multidimensional tensors

In [3]:
# here we will create tensors more than 3
tensor_nd=tf.constant([
    [
    [[1,200,3,4], 
    [4,3,200,1]],

    [[-100,2,5,8],
    [5,6,78,900]]
    ],

    [
    [[1,2,3,4], 
    [4,3,2,1]],

    [[-1,2,5,8],
    [5,6,78,9]]
    ]
])
print("4D tensor is\n", tensor_nd)

4D tensor is
 tf.Tensor(
[[[[   1  200    3    4]
   [   4    3  200    1]]

  [[-100    2    5    8]
   [   5    6   78  900]]]


 [[[   1    2    3    4]
   [   4    3    2    1]]

  [[  -1    2    5    8]
   [   5    6   78    9]]]], shape=(2, 2, 2, 4), dtype=int32)


### converting numpy array into tensors

In [4]:
# creating a numpy array 
np_array=np.array([1,2,3])
print("Original array is\n", np_array)
print("-"*50)

# now converting above array into tensor
to_tensor=tf.convert_to_tensor(np_array)
print("Converted tensor is \n", to_tensor)

Original array is
 [1 2 3]
--------------------------------------------------
Converted tensor is 
 tf.Tensor([1 2 3], shape=(3,), dtype=int32)


### eye method: It is used to create an identity matrix of given size

In [5]:
# creating an identity matrix using eye method
matrix_using_eye=tf.eye(
    num_rows=3, # number of rows specify the number of elements
    # row define the number of dimensions
    num_columns=None # columns 
    # here None means there will be the same number of columns as the number of rows
)
print(matrix_using_eye)
print("-"*50)

# to print different number in diagonals
print(5*matrix_using_eye)
print("-"*50)

# now making some changes in eye method
matrix_using_eye_2=tf.eye(
    num_rows=5,
    num_columns=4,
    dtype=tf.dtypes.bool # will create boolean type matrix
    # we can specify any dtype here
)
print(matrix_using_eye_2)
print("-"*50)

# now creating matrix including batch number as well
# batch number determines the number of matrix we need
matrix_using_eye_3=tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=[3,] # means there will be three matrices
)
print(matrix_using_eye_3)
print("-"*50)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]], shape=(3, 3), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]
 [False False False False]], shape=(5, 4), dtype=bool)
--------------------------------------------------
tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape=(3, 3, 4), dtype=float32)
--------------------------------------------------


### fill method: it is used to create a tensor of any order by passing a value

In [6]:
# creating tensor using fill method
matrix_using_fill_1=tf.fill([2,3], 5) # will create 2*3 matrix with 5 as elements
print(matrix_using_fill_1)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


### ones method= it is used to create a matrix with all values equal to 1

In [7]:
matrix_using_ones=tf.ones([2,3,2]) # will create a 3d matrix of ones
# we can also define the dtype inside it
print(matrix_using_ones)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(2, 3, 2), dtype=float32)


### ones_like method : it is used to change the existing matrix values as 1

In [8]:
# from above code we have following matrix with different values
print("2D tensor is\n", tensor_2d)
print("="*50)

# now changing above matrix values into 1
matrix_using_like_ones=tf.ones_like(tensor_2d)
print("The changed matrix is\n", matrix_using_like_ones)

2D tensor is
 tf.Tensor(
[[1 2 3 4]
 [4 3 2 1]], shape=(2, 4), dtype=int32)
The changed matrix is
 tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]], shape=(2, 4), dtype=int32)


### zeros : it is used to create a matrix with all elements as 0

In [9]:
matrix_using_zeros=tf.zeros([2,3]) # will create a 2*3 matrix with all elements as 0
print(matrix_using_zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


### zeros_like: it is used to change the values of a matrix into 0

In [10]:
# from above code we have following matrix with different values
print("2D tensor is\n", tensor_2d)
print("="*50)

# now changing above matrix values into 0
matrix_using_like_zeros=tf.zeros_like(tensor_2d)
print("The changed matrix is\n", matrix_using_like_zeros)

2D tensor is
 tf.Tensor(
[[1 2 3 4]
 [4 3 2 1]], shape=(2, 4), dtype=int32)
The changed matrix is
 tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]], shape=(2, 4), dtype=int32)


### rank : it is the number of dimensions of a matrix

In [11]:
# from above code we have following matrix with different values
print("2D tensor is\n", tensor_2d)
print("="*50)

# now checking the rank of above matrix 
rank_of_matrix=tf.rank(tensor_2d)
print("The rank of above matrix is\n", rank_of_matrix) # rank must be 2 as this is a 2d tensor

2D tensor is
 tf.Tensor(
[[1 2 3 4]
 [4 3 2 1]], shape=(2, 4), dtype=int32)
The rank of above matrix is
 tf.Tensor(2, shape=(), dtype=int32)


### size : it determines the total number of elements present in a tensor

In [12]:
# from above code we have following matrix with different values
print("2D tensor is\n", tensor_2d)
print("="*50)

# now determining the size of above tensor
size_of_tensor=tf.size(tensor_2d)
print("The size of above tensor is\n", size_of_tensor)

2D tensor is
 tf.Tensor(
[[1 2 3 4]
 [4 3 2 1]], shape=(2, 4), dtype=int32)
The size of above tensor is
 tf.Tensor(8, shape=(), dtype=int32)


### random.normal : it is used to create a tensor with the random values

In [13]:
# creating a tensor with random values
tensor_random=tf.random.normal(
    shape=[3,4],
    mean=100.0, # here mean means we need values close to it
    # dtype=tf.dtypes.int32
)
print("The tensor with random values is\n", tensor_random)

The tensor with random values is
 tf.Tensor(
[[ 99.45395   99.30597  100.191246  99.54784 ]
 [100.65318   99.27182   99.900635 100.17094 ]
 [101.1785    99.29507   99.962814 100.86732 ]], shape=(3, 4), dtype=float32)


### random.uniform: it is also used to create a tensor with random values

In [14]:
tensor_random_uni=tf.random.uniform(
    [4,3], # will create a 4*3 matrix
    minval=1, # defines the minimum start range
    maxval=20, # defines the maximum end range
)
print("The tensor with random values is\n", tensor_random_uni)

The tensor with random values is
 tf.Tensor(
[[ 4.774497  12.35201    5.759293 ]
 [18.638819   6.5293083 10.340546 ]
 [16.206982   4.660458  13.903197 ]
 [16.984875   2.1746283  8.484016 ]], shape=(4, 3), dtype=float32)


## Indexing in tensors

In [15]:
tensor=tf.constant([1,2,3,4,5,6,7,8,9])
# to get the first 5 elements
print("The first five elements form above tensor are\n", tensor[0:5])
print("="*50)

# getting elements with some step size
print("The first five elements with step size 2 are\n", tensor[0:5:2])

The first five elements form above tensor are
 tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
The first five elements with step size 2 are
 tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [16]:
# indexing in higher than 1D tensor
higher_tensor=tf.constant([
    [1,2,3,0],
    [2,1,45,8],
    [7,5,8,9],
    [5,4,6,99]
])
# getting the values of the first 2 rows
# In 2d or higher we use following formula to slice the values or rows or columns
# [rows , columns]
print("The first 3 rows are\n", higher_tensor[0:2,0:3]) # will take 2 rows with 3 columns
print("-"*50)

# taking only single row with columns
print("The 3rd row is\n", higher_tensor[2 , :])
print("-"*50)

# skipping a column from above 3rd row tensor
print("The 3rd row by skipping a column is\n", higher_tensor[2 , 1:]) # will take columns from 1st index to the rest by skipping 0th index
print("-"*50)

The first 3 rows are
 tf.Tensor(
[[ 1  2  3]
 [ 2  1 45]], shape=(2, 3), dtype=int32)
--------------------------------------------------
The 3rd row is
 tf.Tensor([7 5 8 9], shape=(4,), dtype=int32)
--------------------------------------------------
The 3rd row by skipping a column is
 tf.Tensor([5 8 9], shape=(3,), dtype=int32)
--------------------------------------------------


## tf.divide : used to divide two tensors and return the result
## tf.math.divide_no_nan : used to divide two tensors and return the result without printing infinity when divided by 0

In [17]:
# creating two tensors
tensor_1=tf.constant([3,6,9,12,11,15])
tensor_2=tf.constant([3,2,4,4,2,3])

# now dividing
tensor_div=tf.divide(tensor_1, tensor_2)
tensor_div

# by divide_no_nan
tensor_3=tf.constant([3,0,4,4,0,3])

# performing division
tesnor_div_no_nan=tf.math.divide_no_nan(tensor_1, tensor_3)
tesnor_div_no_nan # this will print 0 instead of infinity where division by 0 is performed

<tf.Tensor: shape=(6,), dtype=float64, numpy=array([1.  , 0.  , 2.25, 3.  , 0.  , 5.  ])>

## tf.add : used to add two tensors
## tf.multiply : used to multiply two tensors of any size
## tf.maximum : used to print the tensor having the max values and will print the shape of the tensor
## tf.minimum : used to print the tensor having the min values and will print the shape of the tensor
## tf.argmax : used to print the position of the max value of a tensor
## tf.argmin : used to print the position of the min value of a tensor
## tf.pow : used to calculate the power of the tensor
## tf.reduce_sum : used to add up all the elements of any dimensional tensor
## tf.reduce_max : used to print the max value of any dimensional tensor
## tf.reduce_min : used to print the min value of any dimensional tensor
## tf.reduce_mean : used to print the mean of a tensor
## tf.reduce_std : used to print the standard deviation of tensor
## tf.reduce_prod : used to print the product of elements of a tensor
## tf.top_k : used to print the max/top value(s) of any dimensional tensor along with its/their positions in separate array

In [18]:
# from previous cell
tensor_add=tf.add(tensor_1, tensor_2) # we can also pass a single element in list and it will be added to all elements of other tensor
tensor_add # will return the addition of previou two tensors

# multiplication
tensor_4=tf.constant([3])
tensor_mul=tf.multiply(tensor_1, tensor_4) # 8 will be multiplied to all elements of tensor_1
print("the multiplication is \n",tensor_mul)

# max tensor 
print("the max tensor is \n",tf.maximum(tensor_1, tensor_2)) # will print the max tensor and position of the max value
print("-"*50)

# min tensor
print("the min tensor is \n",tf.minimum(tensor_1, tensor_2))
print("-"*50)

# arg_max will tell the positon of the max value of a tensor
print(tensor_1) # print the original tensor to display the elements
print("the max value is \n",tf.argmax(tensor_1)) 
print("-"*50)

# power of tensor
print("the power of tensor is \n",tf.pow(tensor_1, tensor_4))
print("-"*50)

# reduce_sum
print("the reduced sum of tensor is \n",tf.reduce_sum(tensor_3d, axis=None, keepdims=False, name=None)) # will add all the elements of 3d tensor
# we can specify the axis as well
# axis = 0 means column sum and 1 means rows will be summed up 
print("-"*50)

# reduce_max
print("the reduced max of a tensor is \n",tf.reduce_max(tensor_3d, axis=None, keepdims=False, name=None))
print("-"*50)

# reduce_min
print("the reduced min of a tensor is \n",tf.reduce_min(tensor_3d, axis=None, keepdims=False, name=None))
print("-"*50)

# reduce_mean
print("The reduced mean of the tensor is \n", tf.reduce_mean(tensor_3d, axis=0, keepdims=False, name=None))
# will print the mean of columns only
print("-"*50)

# reduce_prod
print("the reduced product of a 2d tensor is \n", tf.reduce_prod(tensor_2d, axis=None, keepdims=False, name=None))
print("-"*50)

# top_k
print("The top values of 2d tensor are \n", tf.math.top_k(tensor_2d, k=1)) # means 1 value form each tensor
print("-"*50)



the multiplication is 
 tf.Tensor([ 9 18 27 36 33 45], shape=(6,), dtype=int32)
the max tensor is 
 tf.Tensor([ 3  6  9 12 11 15], shape=(6,), dtype=int32)
--------------------------------------------------
the min tensor is 
 tf.Tensor([3 2 4 4 2 3], shape=(6,), dtype=int32)
--------------------------------------------------
tf.Tensor([ 3  6  9 12 11 15], shape=(6,), dtype=int32)
the max value is 
 tf.Tensor(5, shape=(), dtype=int64)
--------------------------------------------------
the power of tensor is 
 tf.Tensor([  27  216  729 1728 1331 3375], shape=(6,), dtype=int32)
--------------------------------------------------
the reduced sum of tensor is 
 tf.Tensor(132, shape=(), dtype=int32)
--------------------------------------------------
the reduced max of a tensor is 
 tf.Tensor(78, shape=(), dtype=int32)
--------------------------------------------------
the reduced min of a tensor is 
 tf.Tensor(-1, shape=(), dtype=int32)
--------------------------------------------------
The 

# lnear algebra using tensorflow

## tf.linalg.matmul : used to multiply two matrices (matrix multiplication rule is also applied)
## tf.transpose : transpose of a matrix
## tf.linalg.inv : used to find the invers of a matix (order must be the same)

In [19]:
# craeting two different matrice
# columns of the first matrix must match the rows of the second matrix
mat_1=tf.constant([
    [1,2,0],
    [5,7,3]])

mat_2=tf.constant([
    [6,5,2],
    [1,5,8],
    [0,2,3]])

mat_3=tf.constant([
    [6,5,2],
    [1,5,8]])

# matmul
print("The product of two matrices is \n", tf.linalg.matmul(mat_1, mat_2, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, output_type=None, name=None))
# we can make any of the optional values to True according to our requirements
print("="*60)

# tf.transpose
print("The transpose of mat_2 is\n", tf.transpose(mat_2))
print("="*60)

# inverse
# we have to change the datatype of the matrix to float
# it is necessary to change the data type from int to any other
mat_2_float=tf.cast(mat_2, tf.float32)
print('The inverse of matrix is \n', tf.linalg.inv(mat_2_float))
print("="*60)

The product of two matrices is 
 tf.Tensor(
[[ 8 15 18]
 [37 66 75]], shape=(2, 3), dtype=int32)
The transpose of mat_2 is
 tf.Tensor(
[[6 1 0]
 [5 5 2]
 [2 8 3]], shape=(3, 3), dtype=int32)
The inverse of matrix is 
 tf.Tensor(
[[ 0.05882354  0.64705884 -1.7647057 ]
 [ 0.17647058 -1.0588235   2.705882  ]
 [-0.11764705  0.7058823  -1.4705881 ]], shape=(3, 3), dtype=float32)


## einsum : used to perform matrix operations using an order of rows and columns our own choice

In [20]:
# matrix multiplication
# from previous two matrices
# printing the actual product using tf
print("prod using tf\n", tf.linalg.matmul(mat_1, mat_2))
print("\n")

# 1) now printing with einsum
print("The product using einsum method is \n", np.einsum('ij, jk -> ik', mat_1, mat_2))
# here i means rows and j means columns
# so for mul we need to have ij and jk means columns of the first mat = rows (j) of the second mat
# the result will yield the ik
print("="*50)


# 2) suppose that we want to find the product of two matrices that does not meet the condition cols=rows
# print the shape of matrices to see the cols and rows
print("The shape of two matrices ready for prod is\n", mat_1.shape, mat_3.shape)
print("since the condition of col=rows fails here")
print("but we can still multiply both of them using einsum as follows\n")

print("The prod of matrices having cols!=rows is \n", np.einsum('ij, ij -> ij', mat_1, mat_3))
print("="*50)


# 3) transpose using einsum
# print the original matrix
print("The original matrix is\n", mat_2)
print("\n")
# now transpose using einsum
print("the transpose using einsum is\n", np.einsum("ij->ji", mat_2))
print("="*50)


# 4) sum using einsum
print("The sum using einsum is \n", np.einsum('ij->j', mat_2))
# the sum will be column wise




prod using tf
 tf.Tensor(
[[ 8 15 18]
 [37 66 75]], shape=(2, 3), dtype=int32)


The product using einsum method is 
 [[ 8 15 18]
 [37 66 75]]
The shape of two matrices ready for prod is
 (2, 3) (2, 3)
since the condition of col=rows fails here
but we can still multiply both of them using einsum as follows

The prod of matrices having cols!=rows is 
 [[ 6 10  0]
 [ 5 35 24]]
The original matrix is
 tf.Tensor(
[[6 5 2]
 [1 5 8]
 [0 2 3]], shape=(3, 3), dtype=int32)


the transpose using einsum is
 [[6 1 0]
 [5 5 2]
 [2 8 3]]
The sum using einsum is 
 [ 7 12 13]


### tf.concat : concat two matrices together

In [21]:
# from frevious cell we have
# a look at the shape/order of matrices
print(mat_1.shape, mat_2.shape, mat_3.shape)
print("The concated result of mat_1 and mat_2 is \n", tf.concat([mat_1, mat_3], axis=1))
# axis=0 means concatenation across the rows and order of matrices does not matter here
# for axis=1 the order must be the same




(2, 3) (3, 3) (2, 3)
The concated result of mat_1 and mat_2 is 
 tf.Tensor(
[[1 2 0 6 5 2]
 [5 7 3 1 5 8]], shape=(2, 6), dtype=int32)


### tf.gather : used to get a range of elements from an array without using traditional slicing

In [22]:
# from previous cell
print("Tensor from previous cell is \n", tensor_1d)
print("\n")
# getting a range of values
print("the range of values from above array is\n", tf.gather(tensor_1d, range(1,4)))
# will print the values from index 1 till 4 means 3 values
print("="*50)

# printing from multi dimensional arrays
print("the original matrix is \n", mat_2, "\n")
print("The range of values is\n", "all elements of the first row are\n", tf.gather(mat_2, [0], axis=0), "\n")
# we can change the value of axis to either 1 or 0
print("all values from the second and the third row are \n", tf.gather(mat_2, [1,2], axis=0), "\n")
print("="*50)

# printing the columns by changing the axis value to 1
print("all column elements from 1st to the 3rd row are\n", tf.gather(mat_2, [0,2], axis=1))



Tensor from previous cell is 
 tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


the range of values from above array is
 tf.Tensor([2 3 4], shape=(3,), dtype=int32)
the original matrix is 
 tf.Tensor(
[[6 5 2]
 [1 5 8]
 [0 2 3]], shape=(3, 3), dtype=int32) 

The range of values is
 all elements of the first row are
 tf.Tensor([[6 5 2]], shape=(1, 3), dtype=int32) 

all values from the second and the third row are 
 tf.Tensor(
[[1 5 8]
 [0 2 3]], shape=(2, 3), dtype=int32) 

all column elements from 1st to the 3rd row are
 tf.Tensor(
[[6 2]
 [1 8]
 [0 3]], shape=(3, 2), dtype=int32)


## tf.ragged : it is a way to create a multi dimensional tensor with non uniform number of columns and rows 

In [23]:
# try to create a tensor using traditonal way in which there will be non_uniformity of cols and rows
# non_uni_tensor= tf.constant([
#     [1,2,3,4],
#     [4,5,2],
#     [7,8,9,4,5]
# ])
# uncomment the above line of code to check

# above tensor has not equal number of columns in each list
# this will display an error maessage

# creating non_uniform tensor using ragged
non_uni_ragged=tf.ragged.constant([
    [1,2,3,4],
    [4,5,2],
    [7,8,9,4,5]
])

non_uni_ragged.shape
# from above output, None in the place of column indicates that there is not equal number of columns in every list

TensorShape([3, None])

## Tensorflow variables 

## var.assign_sub : is used to subtract the elements of created var_tensor from the new given list of the same order
## var.assign_add : similar but opposite to above one 

In [28]:
# creating a tensor and will name it afterwards
x_tensor=tf.constant([1,22,3,4,5])
# now we will make it a variable and name it
x_tensor_var=tf.Variable(x_tensor, name='x_tens_var')
print("The tensor variable is \n", x_tensor_var)
print("="*50)

# assign_sub
print("The subtracted result is\n", x_tensor_var.assign_sub([4,2,5,8,9]))
print("="*50)

# assign_add
print("The added result is\n", x_tensor_var.assign_add([4,2,5,8,9]))
print("="*50)



The tensor variable is 
 <tf.Variable 'x_tens_var:0' shape=(5,) dtype=int32, numpy=array([ 1, 22,  3,  4,  5])>
The subtracted result is
 <tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([-3, 20, -2, -4, -4])>
The added result is
 <tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 1, 22,  3,  4,  5])>
